-----------------------------------------------
--EJERCICIO 1
-----------------------------------------------

USE master
GO

IF DB_ID('BD_COMPUTER_SAC')IS NOT NULL
BEGIN
DROP DATABASE BD_COMPUTER_SAC 
END
GO

CREATE DATABASE BD_COMPUTER_SAC
ON
(
NAME=BD_COMPUTER_SAC_PRI,
FILENAME='C:\DATA\COMPUTO\BD_COMPUTER_SAC_PRI.MDF',
SIZE=10,
MAXSIZE=UNLIMITED,
FILEGROWTH=5MB
),
(
NAME=BD_COMPUTER_SAC_SEC,
FILENAME='C:\DATA\COMPUTO\BD_COMPUTER_SAC_SEC.NDF',
SIZE=10,
MAXSIZE=25,
FILEGROWTH=5%
)
LOG ON (
NAME=BD_COMPUTER_SAC_LOG,
FILENAME='C:\DATA\COMPUTO\BD_COMPUTER_SAC_LOG.LDF',
SIZE=8,
MAXSIZE=50,
FILEGROWTH=10%
)
GO

SP_HELPDB BD_COMPUTER_SAC
GO

------------------------------------------------------------
--EJERCICIO 2
------------------------------------------------------------

USE BD_COMPUTER_SAC
GO

IF OBJECT_ID('CATEGORIA') IS NOT NULL
BEGIN  
  DROP TABLE CATEGORIA
END
GO
CREATE TABLE CATEGORIA
(
COD_CATEGORIA CHAR(7)   NOT NULL,
NOMBRE	VARCHAR(20)		NOT NULL,
PRIMARY KEY (COD_CATEGORIA),
)
GO

IF OBJECT_ID('PRODUCTO') IS NOT NULL
BEGIN  
  DROP TABLE PRODUCTO
END
GO
CREATE TABLE PRODUCTO
(
ID_PRODUCTO  CHAR(6)   NOT NULL,
NOMBRE_PROD  VARCHAR(45) NOT NULL,
DESCRIPCION  VARCHAR(100) NOT NULL,
PRECIO_VENTA  MONEY    NOT NULL,
STOCK_MINIMO  INT     NULL,
STOCK_MAXIMO  INT     NULL,
STOCK_ACTUAL  INT     NOT NULL,
FECHA_VENC	  DATE	  NOT NULL,
PRECIO_COSTO  MONEY	  NOT NULL,
COD_CATEGORIA CHAR(7)   NOT NULL,
PRIMARY KEY (ID_PRODUCTO),
FOREIGN KEY (COD_CATEGORIA) REFERENCES CATEGORIA
)
GO

IF OBJECT_ID('EMPLEADO') IS NOT NULL
BEGIN  
  DROP TABLE EMPLEADO
END
GO
CREATE TABLE EMPLEADO
(
idEmpleado  CHAR(10)   NOT NULL,
nomEmpleado  VARCHAR(50) NOT NULL,
apeEmpleado  VARCHAR(50) NOT NULL,
fnaEmpleado  DATE		NOT NULL,
finEmpleado  DATE		NOT NULL,
sueEmpleado  MONEY    NOT NULL,
PRIMARY KEY (idEmpleado),
)
GO

IF OBJECT_ID('DETALLE_BOLETA') IS NOT NULL
BEGIN
  DROP TABLE DETALLE_BOLETA
END
GO
CREATE TABLE DETALLE_BOLETA
(
NUM_BOLETA   CHAR(10)       NOT NULL,
ID_PRODUCTO  CHAR(6)		NOT NULL,
CANTIDAD     INT            NULL,
IMPORTE      MONEY          NOT NULL,
idEmpleado	 CHAR(10)		NOT NULL,
PRIMARY KEY (NUM_BOLETA, ID_PRODUCTO),
FOREIGN KEY (idEmpleado) REFERENCES EMPLEADO,
FOREIGN KEY (ID_PRODUCTO) REFERENCES PRODUCTO,
)
GO

------------------------------------------------------------
--EJERCICIO 3
------------------------------------------------------------

ALTER TABLE CATEGORIA
ADD CONSTRAINT CHK_COD_CATEGORIA_CATEGORIA
CHECK (COD_CATEGORIA LIKE 'T[0-9][0-9][0-9][0-9]');

ALTER TABLE PRODUCTO
ADD CONSTRAINT CHK_COD_CATEGORIA_PRODUCTO
CHECK (COD_CATEGORIA LIKE 'T[0-9][0-9][0-9][0-9]');

ALTER TABLE EMPLEADO
ADD CONSTRAINT UQ_nomEmpleado_apeEmpleado
UNIQUE (nomEmpleado, apeEmpleado);

ALTER TABLE PRODUCTO
ADD CONSTRAINT DF_STOCK_MAXIMO_PRODUCTO
DEFAULT 0 FOR STOCK_MAXIMO;

sp_help CATEGORIA
GO

sp_help EMPLEADO
GO

sp_help PRODUCTO
GO

