---ACTIVANDO LA BASE DE DATOS MASTER

USE MASTER

GO

----CREANDO NUEVA BASE DE DATOS

----COMPUTER_CORP_SA

IF DB_ID('COMPUTER_CORPO_SAC')IS NOT NULL

BEGIN

 DROP DATABASE COMPUTER_CORPO_SAC

END

GO

CREATE DATABASE COMPUTER_CORPO_SAC

-----VERIFICANDO LA BASE CREADA

SP_HELPDB COMPUTER_CORPO_SAC

GO

---BASE ACTIVA COMPUTER_CORPO_SA

USE COMPUTER_CORPO_SAC

GO

---CREANDO UNA NUEVA TABLA LLAMADA : CATEGORIA_COMPU

IF OBJECT_ID('CATEGORIA_COMPU') IS NOT NULL

BEGIN  

  DROP TABLE CATEGORIA_COMPU

END

GO

CREATE TABLE CATEGORIA_COMPU

(

COD_CATEGORIA  CHAR(3)   NOT NULL,

NOMBRE     VARCHAR(25) NOT NULL,

PRIMARY KEY (COD_CATEGORIA)

)

GO

----CREANDO UNA NUEVA TABLA PRODUCTO DENTRO DEL ESQUEMA VENTAS



IF OBJECT_ID('PRODUCTO_COMPU') IS NOT NULL

BEGIN  

  DROP TABLE PRODUCTO_COMPU

END

GO

CREATE TABLE PRODUCTO_COMPU

(

ID_PRODUCTO  CHAR(6)   NOT NULL,

NO_SERIE    VARCHAR(100) NOT NULL,

NOMBRE_PROD  VARCHAR(45) NOT NULL,

DESCRIPCION  VARCHAR(100) NOT NULL,

PRECIO_VENTA  MONEY    NOT NULL,

PRECIO_COSTO  MONEY    NOT NULL,

STOCK_MINIMO  INT     NULL,

STOCK_MAXIMO  INT     NULL,

STOCK_ACTUAL  INT     NOT NULL,

COD_CATEGORIA CHAR(3)   NOT NULL,

PRIMARY KEY (ID_PRODUCTO),

FOREIGN KEY (COD_CATEGORIA) REFERENCES CATEGORIA_COMPU

)

GO

---CREANDO UNA NUEVA TABLA LLAMADA : CLIENTE_COMPU 

IF OBJECT_ID('CLIENTE_COMPU') IS NOT NULL

BEGIN  

  DROP TABLE CLIENTE_COMPU

END

GO

CREATE TABLE CLIENTE_COMPU

(

ID_CLIENTE    CHAR(6)     NOT NULL,

DNI_CLIENTE    CHAR(8)     NOT NULL,

NOM_CLIENTE    VARCHAR(100)  NOT NULL,

APE_PAT_CLIENTE  VARCHAR(60)   NOT NULL,

APE_MAT_CLIENTE  VARCHAR(60)   NOT NULL,

DIR_CLIENTE    VARCHAR (100)  NOT NULL,

MOV_CLIENTE    CHAR(15)    NOT NULL,

EMAIL_CLIENTE   VARCHAR(100)  NOT NULL

CONSTRAINT KP_CLIENTE PRIMARY KEY (ID_CLIENTE)

)

GO

---CREANDO UNA NUEVA TABLA LLAMADA : DETALLE_BOLETA EN ESQUEMA VENTAS

IF OBJECT_ID('DETALLE_BOLETA') IS NOT NULL

BEGIN  

  DROP TABLE DETALLE_BOLETA

END

GO

CREATE TABLE DETALLE_BOLETA

(

NUM_BOLETA   CHAR(8)   NOT NULL,

ID_PRODUCTO   CHAR(6)   NOT NULL,

ID_CLIENTE   CHAR(6)   NOT NULL,

CANTIDAD    INT     NOT NULL,

IMPORTE     MONEY    NOT NULL,

ID_EMPLEADO   CHAR(8)   NOT NULL

CONSTRAINT KP_DBOLETA PRIMARY KEY (NUM_BOLETA,ID_PRODUCTO)

CONSTRAINT FK_DBOLETACLIE FOREIGN KEY(ID_CLIENTE)REFERENCES CLIENTE_COMPU

)

GO

----DML

---LENGUAJE DE MANIPULACION DE DATOS

----INSERT INTO



INSERT INTO CATEGORIA_COMPU

VALUES

('C01','MAINBOARD'),

('C02','PROCESADORES'),

('C03','FUENTES'),

('C04','CASE'),

('C05','PARLANTES'),

('C06','MONITORES'),

('C07','TECLADOS'),

('C08','T_VIDEO'),

('C09','T_SONIDO'),

('C10','MOUSE'),

('C11','TECLADOS'),

('C12','M_RAM'),

('C13','ESTABILIZADORES'),

('C14','UPS')

GO

------VOLVER A INSERTAR REGISTROS

INSERT INTO CATEGORIA_COMPU

VALUES

('C15','T_USB'),

('C16','POWERCERT'),

('C17','IMPRESORAS'),

('C18','T_RED'),

('C19','CAMARAS'),

('C20','TV'),

('C21','BLUERAY'),

('C22','GRABADORES'),

('C23','SMARTPHONE'),

('C24','T_HDMI'),

('C25','GAME')

GO

----CONSULTANDO LOS REGISTROS DE LA TABLA CATEGORIA_COMPU

SELECT * FROM CATEGORIA_COMPU

GO

----USANDO DELETE

----ELIMINANDO LOS REGISTROS DE C15 A C25

DELETE FROM CATEGORIA_COMPU

WHERE COD_CATEGORIA BETWEEN 'C15' AND 'C25'

GO



----CONSULTANDO LOS REGISTROS DE LA TABLA CATEGORIA_COMPU

SELECT * FROM CATEGORIA_COMPU

GO

---ACTUALIZAR REGISTROS

---UTILIZANDO UPDATE

UPDATE CATEGORIA_COMPU

SET  NOMBRE='T_DVI'

WHERE COD_CATEGORIA='C13'



----CONSULTANDO LOS REGISTROS DE LA TABLA CATEGORIA_COMPU

SELECT * FROM CATEGORIA_COMPU

GO

-----VOLVER A INSERTAR REGISTROS

INSERT INTO CATEGORIA_COMPU

VALUES

('C15','T_USB'),

('C16','POWERCERT'),

('C17','IMPRESORAS'),

('C18','T_RED'),

('C19','CAMARAS'),

('C20','TV'),

('C21','BLUERAY'),

('C22','GRABADORES'),

('C23','SMARTPHONE'),

('C24','T_HDMI'),

('C25','GAME')

GO

----CONSULTANDO LOS REGISTROS DE LA TABLA CATEGORIA_COMPU

SELECT * FROM CATEGORIA_COMPU

GO

----INSERTANDO REGISTROS EN TABLA PRODUCTO_COMPU

INSERT INTO PRODUCTO_COMPU

VALUES

('P00001','HK8023456','MAINBOARD ASUS B450 PREMIE','TARJETA PRINCIPAL',500.00,400.00,'20','100','50','C01'),

('P00002','FRT657YU84','MAINBOARD GIGABYTE B550 ','TARJETA PRINCIPAL',550.00,450.00,'20','100','30','C01'),

('P00003','QW23E4RTY7','TECLADO GENIUS MODELO 345','TECLADO INALAMBRICO', 30.00, 35.00, '50','200','100', 'C10'),

('P00004','FGRT67YUU89I','PARLANTES MICRONICS RT466','SISTEMA DE PARLANTES', 100.00, 120.00,'10','30','20','C05'),

('P00005','ERTFGTY456TY78','MONITOR LED SAMSUNG 40 PULGADAS','MONITOR LED',250.00,280.00,'30','60','35','C06'),

('P00006','FSE34WQ256Y','MONITOR LED AOC 40 PULGADAS','MONITOR LED',255.00,290.00,'30','60','50','C06'),

('P00007','56TY7801WE4','MONITOR LED LG 40 PULGADAS','MONITOR LED',255.00,290.00,'30','60','50','C06'),

('P00008','3456TEE34YU','DISCO DURO SEGATE 2TB','DISCO DURO MAGNETICO',250.00,300.00,'50','100','70','C25'),

('P00009','T45RTGFD23R5','DISCO DURO TOSHIBA 4TB','DISCO DURO MAGNETICO',260.00,310.00,'55','100','80','C25'),

('P00010','34EQQ2DFU8','DISCO SSD TOSHIBA 4TB','DISCO ESTADO SOLIDO',350.00,400.00,'55','100','60','C25'),

('P00011','345REQ67FJ1','FUENTE PC 80+ CORSAIR 700 W','FUENTE DE ENERGIA CERTIFICADA',250.00,300.00,'40','100','36','C16'),

('P00012','12WQ355RFD','FUENTE PC 85+ DTC 600 W','FUENTE DE ENERGIA CERTIFICADA',240.00,280.00,'30','100','60','C16'),

('P00013','34ER6TY8UGGW3','TECLADO MICROSOFT MODELO 265','TECLADO ERGONO USB', 32.00, 40.00, '56','180','79', 'C10'),

('P00015','2QSADFE4912QS','CASE MICRONICS MODELO MIC4569','CASE PARA GAME', 100.00, 140.00, '40','100','48', 'C04'),

('P00016','MRTF4445RT67','CASE TELMAKET MODELO 23456','CASE PARA GAME', 130.00, 200.00, '40','100','70', 'C04'),

('P00017','Q213WE5R6T7','PROCESADOR INTEL 9800 DE 3.6 GHZ','PROCESADOR DE INTEL 8 NUCLEOS ', 700.00, 900.00, '40','100','70', 'C02'), 

('P00018','34EWR6TG','PROCESADOR AMD RYZEN 7800 DE 3.6 GHZ','PROCESADOR DE AMD 8 NUCLEOS ', 500.00, 580.00, '40','100','60', 'C02'),

('P00019','567YU890Y', 'MEMORIA RAM DDR4 DE KINGSTON 16 GB','MODULO DE MEMORIA DIMM ', 180.00, 250.00, '40','100','50', 'C12'),

('P00020','WWEESD34567Y8','MEMORIA RAM DDR4 DE KINGSTON 8 GB','MODULO DE MEMORIA DIMM ', 150.00, 200.00, '40','100','40', 'C12')

GO

----CONSULTANDO TODOS LOS REGISTROS DE LA TABLA CATEGORIA_COMPU

SELECT * FROM PRODUCTO_COMPU

GO

---MOSTRANDO CONSULTA DE CIERTOS CAMPOS CON UN ALIAS

SELECT ID_PRODUCTO AS [CODIGO],

    NOMBRE_PROD AS [NOMBRE DE PRODUCTO],

		PRECIO_VENTA AS [PRECIO VENTA],

		STOCK_ACTUAL AS [CANDIDAD ]

FROM PRODUCTO_COMPU

GO



----ORDENADO

---USANDO ORDER BY DE FORMA DESCENDENTE

SELECT ID_PRODUCTO AS [CODIGO],

    NOMBRE_PROD AS [NOMBRE DE PRODUCTO],

		PRECIO_VENTA AS [PRECIO VENTA],

		STOCK_ACTUAL AS [CANTIDAD ]

FROM PRODUCTO_COMPU

ORDER BY NOMBRE_PROD DESC

GO

---USANDO ORDER BY DE FORMA ASCENDENTE

SELECT TOP 3 ID_PRODUCTO AS [CODIGO],

       NOMBRE_PROD AS [NOMBRE DE PRODUCTO],

		   PRECIO_VENTA AS [PRECIO VENTA],

		   STOCK_ACTUAL AS [CANTIDAD ]

FROM PRODUCTO_COMPU

GO

---MOSTRANDO LOS PRIMEROS 10 REGISTROS

SELECT TOP 10 ID_PRODUCTO AS [CODIGO],

        NOMBRE_PROD AS [NOMBRE DE PRODUCTO],

		    PRECIO_VENTA AS [PRECIO VENTA],

		    STOCK_ACTUAL AS [CANTIDAD ]

FROM PRODUCTO_COMPU

GO

----CONSULTAR POR LOS PRODUCTOS CON PRECIOS MENORES A 400

SELECT ID_PRODUCTO AS [CODIGO],

    NOMBRE_PROD AS [NOMBRE DE PRODUCTO],

		PRECIO_VENTA AS [PRECIO VENTA],

		STOCK_ACTUAL AS [CANTIDAD ]

FROM PRODUCTO_COMPU

WHERE PRECIO_VENTA < 400

GO

----CONSULTAR POR LOS PRECIOS SUPERIORES A 600 

SELECT ID_PRODUCTO AS [CODIGO],

    NOMBRE_PROD AS [NOMBRE DE PRODUCTO],

		PRECIO_VENTA AS [PRECIO VENTA],

		STOCK_ACTUAL AS [CANTIDAD ]

FROM PRODUCTO_COMPU

WHERE PRECIO_VENTA > 600

GO

---MUESTRE LOS PRODUCTOS QUE INICIEN CON P

SELECT ID_PRODUCTO AS [CODIGO],

    NOMBRE_PROD AS [NOMBRE DE PRODUCTO],

		PRECIO_VENTA AS [PRECIO VENTA],

		STOCK_ACTUAL AS [CANTIDAD ]

FROM PRODUCTO_COMPU

WHERE NOMBRE_PROD LIKE 'P%'

GO

---MUESTRE LOS PRODUCTOS QUE TENGAN COMO SEGUNDA LETRA "A"

SELECT ID_PRODUCTO AS [CODIGO],

    NOMBRE_PROD AS [NOMBRE DE PRODUCTO],

		PRECIO_VENTA AS [PRECIO VENTA],

		STOCK_ACTUAL AS [CANTIDAD ]

FROM PRODUCTO_COMPU

WHERE NOMBRE_PROD LIKE '_A%'

GO

---MUESTRE LOS PRODUCTOS QUE INICIEN CON "M" o "P"

SELECT ID_PRODUCTO AS [CODIGO],

    NOMBRE_PROD AS [NOMBRE DE PRODUCTO],

		PRECIO_VENTA AS [PRECIO VENTA],

		STOCK_ACTUAL AS [CANTIDAD ]

FROM PRODUCTO_COMPU

WHERE NOMBRE_PROD LIKE '[M-P]%'

GO

---CONSULTA CON INNER JOIN

SELECT *

  FROM PRODUCTO_COMPU PRO

  INNER JOIN CATEGORIA_COMPU CAT

  ON PRO.COD_CATEGORIA=CAT.COD_CATEGORIA

GO

